version: '2'
services:
  rails-container:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - /var/tmp
      - ./application:/app
    depends_on:
      - mysql-container
    extends:
      file: ./docker/mysql/password.yml
      service: password
  mysql-container:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes_from:
      - db-container
    extends:
      file: ./docker/mysql/password.yml
      service: password
    depends_on:
      - db-container
  nginx-container:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes_from:
      - rails-container
  db-container:
    image: busybox
    volumes:
      - db-volume:/var/lib/mysql/
volumes:
  db-volume:
